### ISSUE TITLE
uv_close() called twice or more?

### ISSUE THREAD

**Issue by dyama** [mattn/mruby-sinatic#3]
Hi, I tried to run examples/basic.rb on MinGW32 env.
But it crash when received a tcp access at first time.

The error message is as follows;

    $ mruby basic.rb
    Assertion failed: 0, file src/win/handle.c, line 71
    
    This application has requested the Runtime to terminate it in an unusual way.
    Please contact the application's support team for more information.
    $ 

This assertion raise in uv_close().

https://github.com/libuv/libuv/blob/v1.0.0/src/win/handle.c#L71

I was change mrblib/sinatic.rb,

    $ git diff sinatic.rb
    diff --git a/mrblib/sinatic.rb b/mrblib/sinatic.rb
    index 45e8ca5..2e18e6e 100644
    --- a/mrblib/sinatic.rb
    +++ b/mrblib/sinatic.rb
    @@ -101,7 +101,7 @@ module Sinatic
               end
             rescue
               c.write("HTTP/1.0 500 Internal Server Error\r\nContent-Length: 22\r\n\r\nInternal Server Error\n") do |x|
    -            c.close if c
    +            c.close if c && !c.closing?
                 c = nil
               end
             end

And run it to be fine. 
sinatic.rb calls uv_close() function in spite of the state of UV object is CLOSING.

How should I about this?

**Comment by mattn** [comment]
Thank you
